# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        object detection: 4
        SLAM: 3
        simultaneous localization and mapping: 3
        transformer: 1

# 通知の閾値
score_threshold: 2
